### ISSUE TITLE
[6pt] Enhancement to compute pixel counts for leveed areas in catchments

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [BradfordBates-NOAA/catchment-enricher#16]
Brad will provide levees data.

Count pixels per catchment. Specify pixel resolution.

**Comment by BradfordBates-NOAA** [comment]
@sophiecress levee areas for the CONUS can be found here: https://drive.google.com/file/d/1ttXvh_7J50S2tAB8Blm470IiBvBnK-Ug/view?usp=sharing

**Comment by sophiecress** [comment]
Just to clarify, I am creating a function that will add up the number of pixels of the LULC raster that correspond to levees in the levee data, adding them up per catchment, and displaying them per catchment in a table?

**Comment by BradfordBates-NOAA** [comment]
Correct. You'll be filling in the `get_levee_count` function from `pixel_counter_functions.py` (https://github.com/BradfordBates-NOAA/catchment-enricher/blob/main/src/pixel_counter_functions.py).

You won't have to display them in a table. You'll just need the function to `return` the `feature_stats` dataframe after the stats have been computed.

**Comment by sophiecress** [comment]
Updates from our discussion yesterday:
1. The sample catchment layer (tif version) does not overlap with any leveed areas. Running the script with the geopackage version, however, does produce a result.
2. Converting the levee vector layer to raster in ArcGIS Pro worked, but the file was too big to convert unless the raster resolution is 50 m. This is the resolution of the saved version I put in the code. The image below shows the raster edges underneath the vector in more detail.
![Capture](https://user-images.githubusercontent.com/98419729/160887956-63b9c11d-554f-4b34-9323-e935dac39ba6.PNG)
