### ISSUE TITLE
[6pt] Enhancement to compute pixel counts NHDPlus waterbodies in catchments

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [BradfordBates-NOAA/catchment-enricher#18]
Brad will provide waterbodies in feature class format. Recommend converting to tif.

Count pixels per catchment. Specify pixel resolution.

**Comment by BradfordBates-NOAA** [comment]
@sophiecress I think the data will be available through this download: https://edap-ow-data-commons.s3.amazonaws.com/NHDPlusV21/Data/NationalData/NHDPlusV21_NationalData_Seamless_Geodatabase_Lower48_07.7z

**Comment by sophiecress** [comment]
Thanks, Brad!

**Comment by sophiecress** [comment]
The rasterized version of the NHD Waterbodies dataset that extends throughout the CONUS is attached below as `nhd_raster.tif`.
[levee_ras50.tif.zip](https://github.com/BradfordBates-NOAA/catchment-enricher/files/8419227/levee_ras50.tif.zip)

**Comment by sophiecress** [comment]
The rasterized version of the NHD Waterbodies dataset for the CONUS, `nhd_raster.tif`, is available at: [https://alabama.box.com/s/2x9otvfiuw63ihcw7fw9f21yudrrp75x](url)

A rasterized version of the NHD Waterbodies dataset for the catchment geopackage used in this repository, `nhdras_clip.tif`, is available at: [https://alabama.box.com/s/5i62d4ijj436mhciut6mryono69c9ryd](url)
