### ISSUE TITLE
[5pt] Add output CSV argument to pixel_counter.py

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [BradfordBates-NOAA/catchment-enricher#9]

**Comment by fastnish** [comment]
@BradfordBates-NOAA Hi Brad- I have added a new .csv portion of the script to what we worked on yesterday but I'm having a bit of trouble testing it out. What was the the entry format for the input files?

It'll ask us this:
pixelCounter.py: error: the following arguments are required: -v/--vector, -r/--raster, -c/--csv

**Comment by BradfordBates-NOAA** [comment]
@fastnish The usage could look like this ```python pixel_counter.py -v <vectorpath> -r <rasterpath> -c <outputcsvpath>```

**Comment by fastnish** [comment]
I see! But when running it from the command line do we just enter:
 
python pixel_counter.py -v //users/nish...etc. -r //users/nish...etc. -c //users/nish...etc.

to get it to run?

**Comment by BradfordBates-NOAA** [comment]
Want to tag up real quick to figure it out?

**Comment by fastnish** [comment]
Sure- I've got a quick meeting from 9:00-9:15, could we meet after?

**Comment by BradfordBates-NOAA** [comment]
Yes, just ping me when you're ready

**Comment by fastnish** [comment]
Hey! Out from my meeting- meet on the normal google meets link?

**Comment by BradfordBates-NOAA** [comment]
Okay jump on here: https://meet.google.com/amp-rbhj-abd?pli=1
